services:
  backend:
    build: ./project
    ports:
      - "5001:5000"
    volumes:
      - ./project:/app
    environment:
      - FLASK_APP=teachmeumb.py
      - FLASK_DEBUG=1
volumes:
  pycache:
    driver: local